name: Build react app

on:
  push:
    branches:
      - develop
      - '**'
      - '*'
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Git User   
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.TOKEN }}
        name: The Bot
        email: bot@example.com

    - name: Build and Deploy
      run: |
        npm i
        npm run deploy