name: Build react app

on:
  push:
    branches:
      - develop
      - '**'
      - '*'
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm i
        npm run deploy